[package]
name = "rabbitmq-sensor"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
amqprs = "2.1.0"
iced = "0.13.1"
iced_futures = { version = "0.13.2", features = ["tokio"] }
rand = "0.8.5"
tokio = "1.43.0"
